server:
  http_listen_port: 9080
  grpc_listen_port: 0

clients:
  - url: "http://loki:3100/loki/api/v1/push"  # Pointing to the Loki container
    tenant_id: ""
    batchwait: 1s
    batchsize: 102400
    timeout: 10s

scrape_configs:
  - job_name: system
    static_configs:
      - targets: ['localhost']
        labels:
          job: varlogs
          __path__: /var/log/*.log  # Scrape all logs from /var/log/*.log
